CREATE DATABASE db2;

USE db2;

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE
(
  Fname VARCHAR(15) NOT NULL,
  Minit VARCHAR(1),
  Lname VARCHAR(15) NOT NULL,
  Ssn CHAR(9) NOT NULL,
  Bdate DATE,
  Address VARCHAR(50),
  Sex CHAR,
  Salary DECIMAL(10,2),
  Super_ssn CHAR(9),
  Dno INT,
  PRIMARY KEY (Ssn)
);

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT
(
  Dname VARCHAR(25) NOT NULL,
  Dnumber INT NOT NULL,
  Mgr_ssn CHAR(9),
  Mgr_start_date DATE,
  PRIMARY KEY (Dnumber),
  UNIQUE (Dname)
);


ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_employee_deptartment FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber);
ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_emp_superssn_ssn FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn);
ALTER TABLE DEPARTMENT ADD CONSTRAINT fk_dept_emp_ssn FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn);

DROP TABLE IF EXISTS PROJECT;
CREATE TABLE PROJECT
(
  Pname VARCHAR(25) NOT NULL,
  Pnumber INT NOT NULL,
  Plocation VARCHAR(15),
  Dnum INT NOT NULL,
  PRIMARY KEY (Pnumber),
  UNIQUE (Pname)
);

ALTER TABLE PROJECT ADD CONSTRAINT fk_project_dept FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber);

DROP TABLE IF EXISTS WORKS_ON;
CREATE TABLE WORKS_ON
(
  Essn CHAR(9) NOT NULL,
  Pno INT NOT NULL,
  Hours DECIMAL(3,1) NOT NULL,
  PRIMARY KEY (Essn, Pno)
);

ALTER TABLE WORKS_ON ADD CONSTRAINT fk_works_emp FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);
ALTER TABLE WORKS_ON ADD CONSTRAINT fk_works_project FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber);